### ISSUE TITLE
user and password for mqtt server

### ISSUE THREAD

**Issue by jblb** [haum/pydihaum#1]
add a way to provide user and password credential to MQTT server if needed

**Comment by JackDesBwa** [comment]
If you have a setup to check the implementation, it can be added to `initialize_mqtt()` in [mqtt.py](https://github.com/haum/pydihaum/blob/main/pydihaum/idihaum/mqtt.py#L48-L57). But then don't forget to force the usage of a secure channel to avoid the password to be transmitted without encryption on the network.

Also, you can use a test to keep the feature optional, enabled only if variables are set. Something like this:
```python
mqtt_user, mqtt_pass = getattr(settings, 'MQTT_USER', False), getattr(settings, 'MQTT_PASS', False)
if mqtt_user and mqtt_pass:
    pass # Do your configuration here
```

**Comment by jblb** [comment]
Agree with you about the use of a secure channel but it's hard to provide and maintain in small systems like ESP8266 based ones
user and password are then the minimal way to secure acces
